import { z } from 'zod';
import { ai } from '../genkit';

// Input schema for image verification
const VerifyImageInputSchema = z.object({
  imageDataUri: z.string().describe('Base64 encoded image data URI'),
});

// Output schema for image verification - following the documentation pattern
const VerifyImageOutputSchema = z.object({
  authenticity: z.enum(['REAL', 'AI_GENERATED', 'UNCERTAIN']).describe('Assessment of image authenticity'),
  reasoning: z.string().describe('A brief, one-sentence explanation for your assessment.'),
  confidence: z.number().min(0).max(100).describe('Confidence level in the assessment (0-100)'),
});

export type VerifyImageInput = z.infer<typeof VerifyImageInputSchema>;
export type VerifyImageOutput = z.infer<typeof VerifyImageOutputSchema>;

// The prompt that instructs the model - following documentation pattern exactly
const verifyImagePrompt = ai.definePrompt({
  name: 'verifyImagePrompt',
  input: { schema: VerifyImageInputSchema },
  output: { schema: VerifyImageOutputSchema },
  prompt: `You are an expert digital image analyst. Your task is to determine if the provided image is a real photograph or an AI-generated image.

**Authenticity Detection Guidelines:**
- **REAL**: The image appears to be a genuine photograph captured by a camera. This includes:
  * Stock photos with watermarks (like Vecteezy, Shutterstock, etc.)
  * Images with minor edits (cropping, color correction, filters)
  * Professional photography with natural lighting and realistic details
  * Images that show real-world physics, consistent shadows, and natural textures

- **AI_GENERATED**: The image shows clear and undeniable signs of being generated by artificial intelligence:
  * Unnatural textures or patterns that don't exist in reality
  * Strange or inconsistent lighting that defies physics
  * Distorted or impossible features (especially hands, faces, text)
  * Repetitive patterns or artifacts
  * Dream-like or non-photorealistic quality
  * Impossible compositions or physics

- **UNCERTAIN**: You cannot definitively determine if the image is real or AI-generated due to:
  * Very low image quality or resolution
  * Heavy manipulation that obscures the original
  * Ambiguous features that could be either real or AI-generated
  * Insufficient information to make a clear judgment

**Analysis Process:**
1. Examine the overall composition and lighting
2. Look for natural vs. artificial textures
3. Check for consistency in details and physics
4. Identify any watermarks or editing artifacts
5. Assess the overall realism and plausibility

Photo: {{media url=imageDataUri}}

Based on your analysis, assess the image's authenticity and provide your reasoning.`,
});

export async function verifyImage(input: VerifyImageInput): Promise<VerifyImageOutput> {
  try {
    const { output } = await verifyImagePrompt(input);
    
    if (!output) {
      throw new Error('No output from image verification');
    }
    
    return output;
  } catch (error) {
    console.error('Error in image verification:', error);
    
    // Return a fallback response if AI verification fails
    return {
      authenticity: 'UNCERTAIN',
      reasoning: 'Unable to verify image authenticity due to technical issues.',
      confidence: 0,
    };
  }
} 